<?php $this->assets->outputJs('headerAdminDashboardJS') ?>
<?php $this->assets->outputCss('headerAdminDashboardCSS') ?>
<ol class="breadcrumb">
    <li class="active">Admin dashboard</li>
</ol>

<div class="row">

    <div class="col-md-6">
        <div class="sortable">
        <div class="sortable-item">
            <div class="panel">
                <div class="panel-heading">
                    Basic admin functionality
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>Changed <a href="" data-toggle="tooltip" data-original-title="Title ticket">ticket</a></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
            <!--
        <div class="sortable-item">
            <div class="panel">
                <div class="panel-heading">
                    Last 5 Ticket
                </div>
                <div class="panel-body">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Date</th>
                            <th>Subject</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>2015-04-06 12:04:41</td>
                            <td><b><a href="">Name Ticket</a></b></td>
                        </tr>
                        <tr>
                            <td>2015-04-06 12:04:41</td>
                            <td><b><a href="">Name Ticket</a></b></td>
                        </tr>
                        <tr>
                            <td>2015-04-06 12:04:41</td>
                            <td><b><a href="">Name Ticket</a></b></td>
                        </tr>
                        <tr>
                            <td>2015-04-06 12:04:41</td>
                            <td><b><a href="">Name Ticket</a></b></td>
                        </tr>
                        <tr>
                            <td>2015-04-06 12:04:41</td>
                            <td><b><a href="">Name Ticket</a></b></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
            -->
    </div>
    </div>
    <div class="col-md-6">
        <!--
        <div class="sortable">
            <div class="sortable-item">
                <div class="panel">
                    <div class="panel-heading">
                        User activity
                    </div>
                    <div class="panel-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>User</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Alex</a></b></td>
                                <td>Changed <a href="" data-toggle="tooltip" data-original-title="Title ticket">ticket</a></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Alex</a></b></td>
                                <td>Changed <a href="" data-toggle="tooltip"
                                               data-original-title="Changed email - email@email.com">email</a></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Alex</a></b></td>
                                <td>Changed <a href="" data-toggle="tooltip" data-original-title="Title ticket">ticket</a></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Alex</a></b></td>
                                <td>Changed <a href="" data-toggle="tooltip" data-original-title="Title ticket">ticket</a></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Alex</a></b></td>
                                <td>Changed <a href="" data-toggle="tooltip" data-original-title="Title ticket">ticket</a></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Alex</a></b></td>
                                <td>Changed <a href="" data-toggle="tooltip" data-original-title="Title ticket">ticket</a></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Alex</a></b></td>
                                <td>Changed <a href="" data-toggle="tooltip" data-original-title="Title ticket">ticket</a></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Alex</a></b></td>
                                <td>Changed <a href="" data-toggle="tooltip" data-original-title="Title ticket">ticket</a></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="sortable-item">
                <div class="panel">
                    <div class="panel-heading">
                        Last 5 Ticket
                    </div>
                    <div class="panel-body">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Date</th>
                                <th>Subject</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Name Ticket</a></b></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Name Ticket</a></b></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Name Ticket</a></b></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Name Ticket</a></b></td>
                            </tr>
                            <tr>
                                <td>2015-04-06 12:04:41</td>
                                <td><b><a href="">Name Ticket</a></b></td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        -->
    </div>
</div>